<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20261004102359 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add athlete_profile for HR zones and onboarding';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE athlete_profile (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, birth_year INT DEFAULT NULL, sex VARCHAR(32) DEFAULT NULL, primary_goal VARCHAR(32) NOT NULL, hr_max INT NOT NULL, hr_rest INT DEFAULT NULL, hr_max_source VARCHAR(32) NOT NULL, zone_method VARCHAR(32) NOT NULL, zones JSON NOT NULL, zones_updated_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, onboarding_completed_at TIMESTAMP(0) WITHOUT TIME ZONE DEFAULT NULL, user_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE UNIQUE INDEX UNIQ_FE95C660A76ED395 ON athlete_profile (user_id)');
        $this->addSql('ALTER TABLE athlete_profile ADD CONSTRAINT FK_FE95C660A76ED395 FOREIGN KEY (user_id) REFERENCES "user" (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE athlete_profile DROP CONSTRAINT FK_FE95C660A76ED395');
        $this->addSql('DROP TABLE athlete_profile');
    }
}
