<?php

declare(strict_types=1);

namespace DoctrineMigrations;

use Doctrine\DBAL\Schema\Schema;
use Doctrine\Migrations\AbstractMigration;

final class Version20260928154110 extends AbstractMigration
{
    public function getDescription(): string
    {
        return 'Add activity chat messages';
    }

    public function up(Schema $schema): void
    {
        $this->addSql('CREATE TABLE activity_chat_message (id INT GENERATED BY DEFAULT AS IDENTITY NOT NULL, content TEXT NOT NULL, role VARCHAR(16) NOT NULL, created_at TIMESTAMP(0) WITHOUT TIME ZONE NOT NULL, activity_id INT NOT NULL, PRIMARY KEY (id))');
        $this->addSql('CREATE INDEX idx_activity_chat_message_activity_id_created_at ON activity_chat_message (activity_id, created_at)');
        $this->addSql('ALTER TABLE activity_chat_message ADD CONSTRAINT FK_F30B3E5781C06096 FOREIGN KEY (activity_id) REFERENCES activity (id) ON DELETE CASCADE NOT DEFERRABLE');
    }

    public function down(Schema $schema): void
    {
        $this->addSql('ALTER TABLE activity_chat_message DROP CONSTRAINT FK_F30B3E5781C06096');
        $this->addSql('DROP TABLE activity_chat_message');
    }
}
